CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_POINTING=y

CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y

CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=2
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=3
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=25
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=1
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=13
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_CRITICAL=6
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MISSING=7

CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_USB=0
