manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: edf5c0814fd3ea202e43aad2d68fd32e882a518c # v0.3.0
      import: app/west.yml
    - name: zmk-adaptive-key
      remote: urob
      revision: e5b335a7b1076cb122582f5a892b118b02a3be34 # main
    - name: zmk-leader-key
      remote: urob
      revision: e894d9afa5164b7fff641db4194fc3d4d6e84bbb # main
    - name: zmk-auto-layer
      remote: urob
      revision: 62c201934711369d50a28df12e1d055d05cb6460 # main
    - name: zmk-behavior-battery-percentage-printer
      remote: badjeff
      revision: e111cbc6ac66caaa157daeb58eda3c8e2b43153a # main
  self:
    path: config
